### ISSUE TITLE
T-max problem

### ISSUE THREAD

**Issue by zhanghongjie101** [aravindsrinivas/curl_rainbow#1]
Why did you choose T-max=100k in your experiment? I think you should train until its convergence. I run your code with T-max=800k on game pong，The CURL and rainbow have the same sample efficiency. Even when T-max=100k, I failed to reproduce the experimental results in the paper.

**Comment by aravindsrinivas** [comment]
T-max is chosen as 100k because the sample-effiicency benchmark is for 100k timesteps (refer to the [SimPLE paper](https://arxiv.org/abs/1903.00374)). 

Training till convergence is beyond the scope of what the paper attempted to do, but if you're interested in that setting, check out DeepMind's paper on using contrastive / predictive losses - https://arxiv.org/abs/2004.14646

"Even when T-max=100k, I failed to reproduce the experimental results in the paper." - Unless you specifically point out what you observe, it is hard to answer. The numbers reported are averaged over 20 seeds. Specifically, for Pong, the mean is -16.5 and the standard-deviation is quite high (2.9) even after 20 seeds.

**Comment by teslacool** [comment]
@aravindsrinivas   Yes, the variance between different seeds is very high. I can not reproduce the performance of Pong in your paper which is 2.1. I see  that the mean is -16.5 in your last answer. So, how did you get the result of 2.1 in your paper?

**Comment by aravindsrinivas** [comment]
@teslacool Updated version of the paper (https://arxiv.org/pdf/2004.04136.pdf) reports -16.5. 2.1 earlier used a few tricks from OTRainbow (multiple update steps per transition) which I have excluded from the latest version due to need for fair comparisons with the baseline Eff Rainbow.
